insert into catalog_items (category, name, price_cents, image_url, tags) values
  ('grocery', 'Whole Milk (1 gal)', 450, null, array['dairy']),
  ('grocery', 'Oat Milk (1/2 gal)', 550, null, array['dairy-free', 'nut-free']),
  ('grocery', 'Large Eggs (dozen)', 380, null, array['eggs']),
  ('grocery', 'Sourdough Bread', 600, null, array['bakery']),
  ('grocery', 'Peanut Butter (16oz)', 425, null, array['nuts']),
  ('grocery', 'Almond Butter (16oz)', 899, null, array['nuts']),
  ('grocery', 'Spaghetti (1lb)', 199, null, array['pasta']),
  ('grocery', 'Marinara Sauce (24oz)', 349, null, array['pasta']),
  ('grocery', 'Chicken Breast (2lb)', 999, null, array['meat']),
  ('grocery', 'Firm Tofu (14oz)', 299, null, array['vegan', 'dairy-free']),
  ('grocery', 'Baby Spinach (5oz)', 349, null, array['produce']),
  ('grocery', 'Bananas (bunch)', 199, null, array['produce']),
  ('grocery', 'Avocados (bag of 4)', 599, null, array['produce']),
  ('grocery', 'Greek Yogurt (32oz)', 549, null, array['dairy']),
  ('grocery', 'Coconut Yogurt (24oz)', 649, null, array['dairy-free']),
  ('grocery', 'Coffee Beans (12oz)', 1299, null, array['pantry']),
  ('grocery', 'Orange Juice (64oz)', 499, null, array['pantry']),
  ('grocery', 'Paper Towels (6-pack)', 899, null, array['household']),
  ('grocery', 'Dish Soap', 399, null, array['household']),
  ('grocery', 'Trash Bags (30ct)', 799, null, array['household']),
  ('gift', 'Ceramic Vase', 6000, null, array['mid-century', 'home']),
  ('gift', 'Espresso Machine', 24999, null, array['kitchen']),
  ('gift', 'Weighted Blanket', 8900, null, array['comfort']),
  ('gift', 'Cast Iron Skillet Set', 7500, null, array['kitchen']),
  ('gift', 'Indoor Herb Garden Kit', 4500, null, array['kitchen', 'plants']),
  ('gift', 'Bluetooth Speaker', 5900, null, array['electronics']),
  ('gift', 'Scented Candle Set', 3200, null, array['home']),
  ('gift', 'French Press', 2800, null, array['kitchen']),
  ('gift', 'Board Game Bundle', 4200, null, array['games']),
  ('gift', 'Cozy Throw Blanket', 3900, null, array['home']),
  ('gift', 'Wine Decanter Set', 5500, null, array['kitchen']),
  ('gift', 'Wireless Charging Pad', 2900, null, array['electronics']),
  ('gift', 'Succulent Trio', 2500, null, array['plants']),
  ('gift', 'Personalized Doormat', 3300, null, array['home']),
  ('gift', 'Charcuterie Board Set', 4700, null, array['kitchen']),
  ('gift', 'Bath Bomb Gift Set', 2200, null, array['comfort']),
  ('gift', 'Instant Camera', 6900, null, array['electronics']),
  ('gift', 'Leather Journal', 1800, null, array['stationery']),
  ('gift', 'Cocktail Kit', 4400, null, array['kitchen']),
  ('gift', 'Air Plant Terrarium', 3100, null, array['plants']),
  ('furniture', 'Mid-Century Sofa', 89900, null, array['mid-century', 'living-room']),
  ('furniture', 'Boucle Accent Chair', 32900, null, array['modern', 'living-room']),
  ('furniture', 'Oak Coffee Table', 24900, null, array['mid-century', 'living-room']),
  ('furniture', 'Rattan Bookshelf', 18900, null, array['boho', 'storage']),
  ('furniture', 'Platform Bed Frame (Queen)', 39900, null, array['modern', 'bedroom']),
  ('furniture', 'Linen Duvet Cover', 12900, null, array['bedroom']),
  ('furniture', 'Walnut Dining Table', 64900, null, array['mid-century', 'dining']),
  ('furniture', 'Set of 4 Dining Chairs', 45900, null, array['dining']),
  ('furniture', 'Jute Area Rug (8x10)', 27900, null, array['boho', 'living-room']),
  ('furniture', 'Floor Lamp', 9900, null, array['lighting']),
  ('furniture', 'Wall Mirror', 14900, null, array['decor']),
  ('furniture', 'TV Console', 29900, null, array['living-room', 'storage']),
  ('furniture', 'Bar Cart', 21900, null, array['boho', 'living-room']),
  ('furniture', 'Nightstand Pair', 19900, null, array['bedroom']),
  ('furniture', 'Desk Chair', 24900, null, array['office']),
  ('furniture', 'Standing Desk', 44900, null, array['office']),
  ('furniture', 'Storage Ottoman', 8900, null, array['living-room']),
  ('furniture', 'Outdoor Bistro Set', 34900, null, array['outdoor']),
  ('furniture', 'Woven Throw Pillows (set of 2)', 4900, null, array['decor']),
  ('furniture', 'Ceramic Table Lamp', 7900, null, array['lighting']);
